INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'CANClient' object has no attribute 'sen_byte'")]) created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py:712>
source_traceback: Object created at (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 384, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 228, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\__main__.py", line 6, in <module>
    sys.exit(cansimconnector())
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\cli.py", line 93, in cansimconnector
    run(main_loop(), debug=True)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\winloop\__init__.py", line 111, in run
    return __asyncio.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\arrowiiiturbodevices.py", line 52, in run
    asyncio.gather(*(obj.run() for obj in self._devices))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 854, in gather
    outer = _GatheringFuture(children, loop=loop)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 712, in __init__
    super().__init__(loop=loop)
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\transponder.py", line 57, in run
  |     async with asyncio.TaskGroup() as tg:
  |                ^^^^^^^^^^^^^^^^^^^
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\transponder.py", line 17, in run_volts
    |     await self._can.sen_byte(self.CAN_ID, 1, int(value))
    |           ^^^^^^^^^^^^^^^^^^
    | AttributeError: 'CANClient' object has no attribute 'sen_byte'. Did you mean: 'send_byte'?
    +------------------------------------
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'CANClient' object has no attribute 'sen_float'")]) created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py:712>
source_traceback: Object created at (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 384, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 228, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\__main__.py", line 6, in <module>
    sys.exit(cansimconnector())
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\cli.py", line 93, in cansimconnector
    run(main_loop(), debug=True)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\winloop\__init__.py", line 111, in run
    return __asyncio.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\arrowiiiturbodevices.py", line 52, in run
    asyncio.gather(*(obj.run() for obj in self._devices))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 854, in gather
    outer = _GatheringFuture(children, loop=loop)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 712, in __init__
    super().__init__(loop=loop)
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\indicators2.py", line 27, in run
  |     async with asyncio.TaskGroup() as tg:
  |                ^^^^^^^^^^^^^^^^^^^
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\indicators2.py", line 17, in run_indicator
    |     await self._can.sen_float(self.CAN_ID, port, value)
    |           ^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'CANClient' object has no attribute 'sen_float'. Did you mean: 'send_float'?
    +------------------------------------
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
WARNING:asyncio:Executing <Task pending name='Task-84' coro=<LedGauge.run_dataref() running at C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py:28> wait_for=<Future pending cb=[Task.task_wakeup()] created at c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\aiohttp\connector.py:958> cb=[TaskGroup._on_task_done()] created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py:161> took 15.391 seconds
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
WARNING:asyncio:Executing <Task pending name='Task-72' coro=<LedGauge.run_dataref() running at C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py:28> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py:922, Task.task_wakeup()] created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py:903> cb=[TaskGroup._on_task_done()] created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py:161> took 28.875 seconds
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ExceptionGroup('unhandled errors in a TaskGroup', [ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")]), ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")]), ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")]), ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")]), ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")]), ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")]), ExceptionGroup('unhandled errors in a TaskGroup', [AttributeError("'Annunciators2' object has no attribute 'send_byte'")])]) created at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py:712>
source_traceback: Object created at (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 384, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 228, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "c:\Users\alexe\.vscode-server\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\__main__.py", line 6, in <module>
    sys.exit(cansimconnector())
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\cli.py", line 93, in cansimconnector
    run(main_loop(), debug=True)
  File "c:\Users\alexe\AppData\Local\hatch\env\virtual\cansimconnector\zVfji5Qb\cansimconnector\Lib\site-packages\winloop\__init__.py", line 111, in run
    return __asyncio.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\arrowiiiturbodevices.py", line 52, in run
    asyncio.gather(*(obj.run() for obj in self._devices))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 854, in gather
    outer = _GatheringFuture(children, loop=loop)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 712, in __init__
    super().__init__(loop=loop)
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 112, in run
  |     async with asyncio.TaskGroup() as tg:
  |                ^^^^^^^^^^^^^^^^^^^
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (7 sub-exceptions)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
    +---------------- 2 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
    +---------------- 3 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
    +---------------- 4 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
    +---------------- 5 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
    +---------------- 6 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
    +---------------- 7 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 41, in run
    |     async with asyncio.TaskGroup() as tg:
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\taskgroups.py", line 145, in __aexit__
    |     raise me from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 31, in run_dataref
      |     await self._update_device()
      |   File "C:\Users\alexe\Development\SimGaugesCAN\src\cansimconnector\arrowiiiturbodevices\annunciators.py", line 38, in _update_device
      |     await self._device.send_byte(self._can_port, led_value)
      |           ^^^^^^^^^^^^^^^^^^^^^^
      | AttributeError: 'Annunciators2' object has no attribute 'send_byte'. Did you mean: 'can_send_byte'?
      +------------------------------------
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cli:Reading config
INFO:cansimconnector.cli:Connecting to services
INFO:cansimconnector.cli:Sim connection init
INFO:cansimconnector.cli:CAN bus init
INFO:cansimconnector.cli:CAN connected
INFO:cansimconnector.cli:Sim connected
INFO:cansimconnector.cli:Connected to services
INFO:cansimconnector.cli:Registering devices
INFO:cansimconnector.cli:Starting main loop
INFO:cansimconnector.cansimlib.canclient:Starting CAN handler
INFO:cansimconnector.cansimlib.xplanewsclient:Starting WebSockets handler
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 23, 8, but no subscribers
INFO:cansimconnector.cansimlib.canclient:Received CAN value from 17, 0, but no subscribers
